### ISSUE TITLE
CallGraph Option Errors

### ISSUE THREAD

**Issue by majestyhao** [secure-software-engineering/soot-infoflow-android#106]
When select RTA,
the error:
```
Exception in thread "main" java.lang.RuntimeException: Incompatible options rta:true and on-fly-cg:true for cg.spark. Use -p cg-.spark on-fly-cg:false when using RTA.
```

**Comment by StevenArzt** [comment]
Have you tried to follow the advice from the exception message and disabled the on-the-fly callgraph mode?

**Comment by majestyhao** [comment]
I just want to report the options suggested by test.java and setupapplication.java may be needed to be changed.
This one is only an example, actually all options regarding callgraph do not work.

**Comment by StevenArzt** [comment]
Now I understand. Thanks for the bug report. I have just fixed the source. You need to update Soot, soot-infoflow, and soot-infoflow-android. New nightly builds will be available by tomorrow.
