### ISSUE TITLE
Error: Could not find or load main class

### ISSUE THREAD

**Issue by ZhengqiaoLi** [secure-software-engineering/soot-infoflow-android#108]
Hi:
    I use CMD 
    "java -cp soot-trunk.jar:soot-infoflow.jar:soot-infoflow-android.jar:slf4j-api-1.7.5.jar:axml-2.0.jar soot.jimple.infoflow.android.TestApps.Test com.example.hello-1.apk /home/lizhengqiao/Documents/adt-bundle-linux-x86-20140321/sdk/platforms"

    But:
    Error: Could not find or load main class soot.jimple.infoflow.android.TestApps.Test
    Why?
Could you help me?

**Comment by Modhi** [comment]
Hi
You are using a colon ' : ' to separate the jars instead of semicolon  ' ; '

-Best,
Modhi
