### ISSUE TITLE
Can FlowDroid Specificed the argument of sourceAndsink files？

### ISSUE THREAD

**Issue by fan123199** [secure-software-engineering/soot-infoflow-android#109]
Such as a line in SourceAndSink.txt 
`<android.os.Bundle: float getFloat(java.lang.String)> -> _SOURCE_`.
Can I use 
`<android.os.Bundle: float getFloat("s")> -> _SOURCE_` instead of the former?
For my result, flowDroid can't not recognise the argument for my run. 
I really want to know how to solve it.

**Comment by StevenArzt** [comment]
FlowDroid expects Soot method signatures in its source/sink definitions. We do not have support for checking parameter values at the moment. You can, however, implement your own SourceSinkManager class (potentially derived from the existing one) and add support for this feature.

**Comment by fan123199** [comment]
thanks，I will try it.

Steven Arzt <notifications@github.com>于2016年3月31日周四 下午10:56写道：
