### ISSUE TITLE
what does "array element type: (filled narr)int" mean?

### ISSUE THREAD

**Issue by njupt-moon** [secure-software-engineering/soot-infoflow-android#112]
@StevenArzt
Hi!
When I use FlowDroid to analyse apks, I always get such output “array element type: (filled narr)int”, I wonder what does it mean? This information I have not met before really bothers me. Does it means some mistakes?
[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
[Spark] Pointer Assignment Graph in 0.4 seconds.
[Spark] Type masks in 0.1 seconds.
[Spark] Pointer Graph simplified in 0.0 seconds.
array element type: (filled narr)int
array element type: (filled narr)int
array element type: (filled narr)int
array element type: (filled narr)int
array element type: (filled narr)int
array element type: (filled narr)int
array element type: (filled narr)int

**Comment by StevenArzt** [comment]
This is an internal debug message printed by Soot. We should remove it, because it doesn't help normal users, but it is nothing to worry about.
