### ISSUE TITLE
Timeout option does not work

### ISSUE THREAD

**Issue by Modhi** [secure-software-engineering/soot-infoflow-android#118]
Hi @StevenArzt 

As indicated in the title , the timeout option does not work, the analysis keeps running until an outOfMemory exception. The usage info for the option states that "--TIMEOUT n Time out after n seconds", however, --timeout 300 does not terminate the analysis after 5 minutes !

Also, I could not find an equivalent in the infoflow configuration settings to the command line option!

Thank you!

**Comment by StevenArzt** [comment]
This feature  is system-dependent and not always reliable. On Linux, you can use the --systimeout parameter instead which uses the /usr/bin/timeout executable. In our tests, that was the most reliable solution.
