### ISSUE TITLE
Get resources based on locale using ARSCFileParser

### ISSUE THREAD

**Issue by WisdomSky** [secure-software-engineering/soot-infoflow-android#121]
I'm not sure if the ARSCFIleParser already has support to getting resources based on specific locale,
but if not, it would be really a good thing to add. :)

**Comment by StevenArzt** [comment]
The ARSCFileParser already gives you a list of configurations which then contain the respective resources. This should already allow you to look for specific locales. Feel free to add more convenient lookup options and open a pull request for your changes.
