### ISSUE TITLE
Specify number of cores that are used for an analysis

### ISSUE THREAD

**Issue by vitaliiavdiienko** [secure-software-engineering/soot-infoflow-android#122]
Hi all,

it turns out that there is no way how to tell FlowDroid how many cores it can use.

I have encountered several usages of `Runtime.getRuntime().availableProcessors()` starting from the current project and up to heros. The way is cool but sometimes I need to run several instances of FlowDroid on the same machine or reserve some CPU time for other processes.

Can we use something like this?
```java
public static int getNumberOfCPUs(){
    	int num;
    	try{
    		num = Integer.parseInt(System.getProperty("numThreads"));
    	}
    	catch(NumberFormatException exc){
    		num =  Runtime.getRuntime().availableProcessors();
    	}
    	return num;
    }
```

then people can use `-DnumThreads=8` as a parameter for the JVM.

Does it possible to come up with some acceptable soltution here?

Thank you in advance,
Vitalii

**Comment by StevenArzt** [comment]
In InfoflowConfiguration, there is a method setMaxThreadNum(). FlowDroid should take this number everywhere unless it is -1 in which case the maximum number of cores available on the machine is used.

**Comment by vitaliiavdiienko** [comment]
Thanks. It seems that `setMaxThreadNum()` is not used at all.

Does it make sense for me to connect it with a new parameter of FlowDroid `--MAXTHREADNUM` and create a pull request?

**Comment by StevenArzt** [comment]
Yes, that would be a good improvement.

**Comment by dfbravo** [comment]
I am unable to limit the number of cores flowdroid uses. I tried using this flag but flowdroid is still using all available cores. Here is the command I used: 

java -XX:+PrintGCTimeStamps -XX:+PrintGC -Xmx20g -cp soot-trunk.jar:soot-infoflow.jar:soot-infoflow-android.jar:slf4j-api-1.7.5.jar:slf4j-simple-1.7.5.jar:axml-2.0.jar soot.jimple.infoflow.android.TestApps.Test "/home/diego/Documents/apks/DU_Browser_Fase_Secure_5.1.0.1_apk-dl.com/DU_Browser_Fase_Secure_5.1.0.1_apk-dl.com.apk" /home/diego/Android/Sdk/platforms/android-19/android.jar --maxthreadnum 1 --nostatic  --aliasflowins --nocallbacks

I used the nightly build from June 14.
![screenshot from 2016-06-22 15-29-20](https://cloud.githubusercontent.com/assets/7070913/16280555/bed0cd84-3885-11e6-92c1-cb5a43d1b873.png)
