### ISSUE TITLE
FlowDroid failed to handle method "java.util.List: java.lang.Object[] toArray(java.lang.Object[])"

### ISSUE THREAD

**Issue by njupt-moon** [secure-software-engineering/soot-infoflow-android#125]
@StevenArzt 
Hi!
Here is the code snapshot:
    $r2 = newarray (java.lang.String)[$i0];
    $r4 = $r0."uk.co.economist.activity.Splash: java.util.List s";
    interfaceinvoke $r4."java.util.List: java.lang.Object[] toArray(java.lang.Object[])"($r2);
    virtualinvoke $r0."uk.co.economist.activity.Splash: void requestPermissions(java.lang.String[],int)"($r2, 200);
Here value $r4 has already been tainted, after execution of statement "interfaceinvoke $r4."java.util.List: java.lang.Object[] toArray(java.lang.Object[])"($r2);", value $r2 should be tainted, but actually FlowDroid does not handle this situation.

**Comment by StevenArzt** [comment]
The EasyTaintWrapper in FlowDroid actually cannot handle this situation (transferring a taint from the base object to a parameter). You need to use a more powerful library handling such as StubDroid: https://github.com/secure-software-engineering/soot-infoflow-summaries.

**Comment by njupt-moon** [comment]
@StevenArzt 
Hi!
In Test.java file in FlowDroid, method "protected static ITaintPropagationWrapper createLibrarySummaryTW()" deals with librarySummaries, since I have little knowledge about SubDroid, here I have two questions:
1. currently, FlowDroid can only deal with one library class at each time?
2. this statement in Test.java seems can not work, "Class clzLazySummary = Class.forName("soot.jimple.infoflow.methodSummary.data.summary.LazySummary");", there is no class named soot.jimple.infoflow.methodSummary.data.summary.LazySummary.
Thanks!

**Comment by StevenArzt** [comment]
The bug in the integration code for StubDroid should be fixed by now.

Concerning your other question: The EasyTaintWrapper provided by FlowDroid by default (if you are not using StubDroid), can only associate taints with one library class at a time, right. That's one of the reasons why we created StubDroid as a better solution.
