### ISSUE TITLE
Retrive paths with caller methods in infoflow results!

### ISSUE THREAD

**Issue by Modhi** [secure-software-engineering/soot-infoflow-android#127]
Hi All,

I'd like to know if there are some calls to retrieve the paths calculated by the PathBuilder (such as ContextInsensitivePathBuilder) in the same form they are displayed on screen including the caller class:method(). the calls printResults and getResults only report the statements but not the callers. is there a way to get the callers??

Example:
on display:

```
[main] INFO soot.jimple.infoflow.Infoflow - The sink virtualinvoke $r7.<org.json.JSONObject: org.json.JSONObject put(java.lang.String,double)>("lng", $d0) in method <com.umeng.analytics.b: void c(android.content.Context,android.content.SharedPreferences)> was called with values from the following sources:
[main] INFO soot.jimple.infoflow.Infoflow - - $d0 = virtualinvoke $r8.<android.location.Location: double getLongitude()>() in method <com.umeng.analytics.b: void c(android.content.Context,android.content.SharedPreferences)>
[main] INFO soot.jimple.infoflow.Infoflow -     on Path: 
[main] INFO soot.jimple.infoflow.Infoflow -      -> <com.umeng.analytics.b: void c(android.content.Context,android.content.SharedPreferences)>
[main] INFO soot.jimple.infoflow.Infoflow -          -> $d0 = virtualinvoke $r8.<android.location.Location: double getLongitude()>()
[main] INFO soot.jimple.infoflow.Infoflow -      -> <com.umeng.analytics.b: void c(android.content.Context,android.content.SharedPreferences)>
[main] INFO soot.jimple.infoflow.Infoflow -          -> virtualinvoke $r7.<org.json.JSONObject: org.json.JSONObject put(java.lang.String,double)>("lng", $d0)

```

calling printResults

```
Found a flow to sink virtualinvoke $r7.<org.json.JSONObject: org.json.JSONObject put(java.lang.String,double)>("lng", $d0), from the following sources:
    - $d0 = virtualinvoke $r8.<android.location.Location: double getLongitude()>()
        on Path [$d0 = virtualinvoke $r8.<android.location.Location: double getLongitude()>(), virtualinvoke $r7.<org.json.JSONObject: org.json.JSONObject put(java.lang.String,double)>("lng", $d0)]
```

Your quick response is highly recommended!
Thank you!

@StevenArzt

**Comment by StevenArzt** [comment]
This is controlled by two options inside the InfoflowAndroidConfiguration class. First, there is the "pathBuilder" which defines the path building algorithm to use. You need to use one that supports path reconstruction such as the ContextInsensitivePathBuilder or the ContextSensitivePathBuilder. Next, there is the option "computeResultPaths" that defines whether result paths should be computed at all or whether only the connected sources and sink, but not the path between them, shall be reported.

The path builders work in the background, you usually do not access them explicitly. You only access the result objects that FlowDroid give you as part of its ResultsAvailableHandler callback. In our test program, we do the printout as follows:

```
				// Report the results
				for (ResultSinkInfo sink : results.getResults().keySet()) {
					print("Found a flow to sink " + sink + ", from the following sources:");
					for (ResultSourceInfo source : results.getResults().get(sink)) {
						print("\t- " + source.getSource() + " (in "
								+ cfg.getMethodOf(source.getSource()).getSignature()  + ")");
						if (source.getPath() != null)
							print("\t\ton Path " + Arrays.toString(source.getPath()));
					}
				}
```

**Comment by jgumana** [comment]
Hi @StevenArzt, if I have something like (as part of a flow): 

buttonSend.setOnClickListener(new OnClickListener() {
...
sms.sendTextMessage("1234", null, DeviceId, null, null);
...
}

changing the value of computeResultPaths should be enough if I want to see the name buttonSend as part of the output? 

Thank you.

**Comment by StevenArzt** [comment]
The button name will most likely not appear in the output, because it is just a variable name without any further semantics. If you need additional information about the UI controls involved in the data flow path, you need to write your own reconstruction algorithm. One approach would be to iterate over all entries in the path and see if they are callbacks associated with a UI element and then map this callback method back to the respective control. This is a bit tricky, though. The good news, on the other hand, is that all required information is already collected in FlowDroid's callback collection process. The calculateSourcesAndSinks() method in the SetupApplication class is a good starting point to see how all this information is stored in FlowDroid.
