### ISSUE TITLE
Questions about processedge

### ISSUE THREAD

**Issue by YYXWJ** [secure-software-engineering/soot-infoflow-android#136]
Dear developers:
    i have understood when the method isCallStmt,isExitStmt and getSuccsOf is invoked. I also find that  processedge is  called as well in the process of contructing dataflow graph. But it  really confused me that  under what  condition it  is called.Would you please explain that ?Thank you very much.
Best wishes!

```
public void run() {
			if (icfg.isCallStmt(edge.getTarget())) {
				processCall(edge,TaskID);
			} else {
				// note that some statements, such as "throw" may be
				// both an exit statement and a "normal" statement
				if (icfg.isExitStmt(edge.getTarget())) {
					try {
						processExit(edge,TaskID);
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
				if (!icfg.getSuccsOf(edge.getTarget()).isEmpty()){
					processNormalFlow(edge,TaskID);
				}	
			}
		}
```
```
@Override
	public boolean processEdge(PathEdge<Unit, Abstraction> edge){
		propagate(edge.factAtSource(), edge.getTarget(), edge.factAtTarget(), null, false, true);
		return true;
	}
```

**Comment by StevenArzt** [comment]
I'm not sure I understand your question. Do you want to know when processEdge() is called or what happens inside processEdge()? In general, this method takes an edge from the worklist and propagates the data flow facts over that edge. It is thus called whenever a worker thread processes an edge. In other words, if there is a taint on a variable on some statement, this taint must then also be propagated across all successor statements in the ICFG. For each such successor, processEdge() is called to propagate over that edge,

**Comment by YYXWJ** [comment]
We want to figure out what kinds of edges can invoke the function **ProcessEdge**()?
According to our study of FlowDroid, we have already concluded the patterns of processing edge, there are three edge processing situations for three different kinds of edges. For example:
1)	If the edge is a call statement, like “_$r3 = staticinvoke <com.example.xiaoby.test_flowdroid.MainActivity: java.lang.String access$000(com.example.xiaoby.test_flowdroid.MainActivity)>($r4);_”it will be processed by **processCall()**. Shown in the annotation line1.
2)	If the edge is an exit statement, like “_return r1;_” it will be processed by **processExit ()**. Shown in the annotation line2.
3)	If the edge is a normal statement, like “_$r4 = $r0.<com.example.xiaoby.test_flowdroid.MainActivity$1: com.example.xiaoby.test_flowdroid.MainActivity this$0>;_”it will be processed by **processNormalFlow ()**. Shown in the annotation line3.

However, among these three situations, there are some edge will invoke the function **ProcessEdge()**. Our question is that which edges will invoke this function to process. Do these edges that processed by the **ProcessEdge()** have the same features or patterns. Does the function **ProcessEdge()** is similar to the three situation above, only processes the edges with specific condition.
In addition, we also wonder what result we can obtain after the method **ProcessEdge()** finished processing the edge. What is the purpose of using this method to process edges. What operations the method make on the edges.

```
public void run() {
			if (icfg.isCallStmt(edge.getTarget())) {
				processCall(edge,TaskID);//line 1
			} else {
				// note that some statements, such as "throw" may be
				// both an exit statement and a "normal" statement
				if (icfg.isExitStmt(edge.getTarget())) {
					try {
						processExit(edge,TaskID);//line 2
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
				if (!icfg.getSuccsOf(edge.getTarget()).isEmpty()){
					processNormalFlow(edge,TaskID);//line 3
				}	
			}
		}

```

**Comment by StevenArzt** [comment]
Now I understand your question. The IFDSSolver class is a general IFDS solver. It starts with the nodes given as seeds and then propagates edges from there until it has reached a fixpoint. For this handling, it keeps a work list that is processed by worker threads. Each task for such a worker thread is an instance of the PathEdgeProcessingTask class. If the solver needs to schedule a new edge for processing, it calls the propagate() method. Propagate() first performs some checks and filters unnecessary edges. If the new edge is really necessary, it creates an instance of the PathEdgeProcessingTask class and puts it on the work list (i.e., schedules it with the executor).

The propagate() method takes arbitrary edges. It does not care which type of edge it is. This will be decided later. When the edge is actually processed by the worker Thread (PathEdgeProcessingTask.run()), the analysis decides on the type of edge and calls the correct processing method (processCall(), processExit(), or processNormalFlow()).

As the propagate() method is protected, it can only be used from inside the solver. Sometimes, however, external code also needs to inject additional edges for processing. Our alias analysis, for example, needs to inject a new edge for every alias it finds. This is the purpose of the processEdge() method: It simply calls propagate(), i.e., makes propagate() available to the outside. The rest is the same as for edges generated within the solver: A new task is created and executed. Only when the task actually runs, the type of edge is decided and the correct processing method is called.
