### ISSUE TITLE
Bad nightly build links

### ISSUE THREAD

**Issue by dillrich** [secure-software-engineering/soot-infoflow-android#140]
Trying to get the nightly builds but the links aren't working.  Trying to find:

soot-inflow.jar
soot-inflow-android.jar
slf4j-apo-1.7.5.jar
slf4j-simple-1.7.5.jar
axml-2.0.jar

**Comment by ericbodden** [comment]
This is a known issue. We are currently in the process of reworking our nightly builds.

**Comment by dillrich** [comment]
Ok, thanks.  Is there an estimated time to get the files hosted?

**Comment by ericbodden** [comment]
Please see other thread, I will close this one.
https://github.com/Sable/soot/issues/696#issuecomment-278600398
