### ISSUE TITLE
How to update target SDK version of apk

### ISSUE THREAD

**Issue by doo1234** [secure-software-engineering/soot-infoflow-android#160]
I am looking for a way of updating targetSDKVersion and compileSdkVersion of apk files. Is this facility currently available in `soot-infoflow-android` ? Couldn't find a help from `soot.jimple.infoflow.android.manifest.ProcessManifest`

**Comment by doomal1234** [comment]
Any update about this ? Is this possible too do with `soot-infoflow-android` ?

**Comment by mbenz89** [comment]
Hi.

I am not a developer of soot-infoflow-android, so I can give you just some pointers here.
As far as I know, you are able to parse manifest files (and other xml files) with FlowDroid. 
To parse the manifest file, use the `ProcessManifest` class. Afterward, you should be able to alter what you want and generate a new file (replace the old one).

Maybe this helps: https://groups.google.com/forum/#!topic/soot-list/NU8zZ9D_5k8

Best,
Manuel

**Comment by StevenArzt** [comment]
The Android manifest parser in FlowDroid is a read-only parser. It does not allow you to change the contents of the manifest, because such a feature is not necessary for the data flow analysis, which is the main purpose of FlowDroid.
