### ISSUE TITLE
How can I find that special method in android sdk is invoked?!

### ISSUE THREAD

**Issue by ehsan-is-everything** [secure-software-engineering/soot-infoflow-android#170]
Hi,

I trying to find a path from dummyMain to the Statement where the special method of SDK (Like rawQuery of Sqlite Library) was invoked. I trying to find it from "Scene.v().getCallGraph()" but there isn't any method with this name in it! Could anyone help me with this problem? Am I right with exploring in CFG of Android App? At the end, I want the sequence of calling methods and classes till rawQuery()! 

Thanks
Ehsan

**Comment by ehsan-is-everything** [comment]
@Alexandre-Bartel @jpstotz @yuki2006 @hjjandy @nguyenLisa

**Comment by maldil** [comment]
You may need to give more details of your code here. What are the soot configurations ? How did you iterate the call graph ?

**Comment by ehsan-is-everything** [comment]
finally, I found the solution. here is the code:
Iterator<Edge> it = cfg.iterator();

		LinkedList<SootMethod> listofTargetMethods = new LinkedList<>();

		while (it.hasNext()) {
			Edge e = it.next();
			if (e.getSrc().method().retrieveActiveBody().toString().contains("rawQuery")) {
				SootMethod targetMethod = e.getSrc().method();
				if (!listofTargetMethods.contains(targetMethod))
					listofTargetMethods.add(targetMethod);
			}
		}
