### ISSUE TITLE
"404 Not Found" reponse from the nightly builded soot bundle URL.

### ISSUE THREAD

**Issue by xcdu** [secure-software-engineering/soot-infoflow-android#172]
https://soot-build.cs.uni-paderborn.de/nightly/soot/sootclasses-trunk-jar-with-dependencies.jar
The link above is not available.

**Comment by mbenz89** [comment]
It moved to: https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/build/

**Comment by xcdu** [comment]
Thanks
