### ISSUE TITLE
code in the Callback method

### ISSUE THREAD

**Issue by yeshen4328** [secure-software-engineering/soot-infoflow-android#176]
I found that soot can't model the **behavior of callback method** like _OnClickListener.OnClick()_. I put some codes int the OnClick(), but the final graph does't contain these codes. I don't know if I write the correct code:
`
 SetupApplication app = new SetupApplication(androidPlatformPath, appPath);         
soot.G.reset(); 
 app.setCallbackFile(CGGenerator.class.getResource("AndroidCallbacks.txt").getFile());  
 app.constructCallgraph(); 
 SootMethod entryPoint = app.getDummyMainMethod();  
 app.printEntrypoints();
CallGraph cg = Scene.v().getCallGraph(); `

**Comment by wowhhh** [comment]
Hello , i have similar questions . 
have you solved this problem ? or found the root cause?
