### ISSUE TITLE
Error: Unable to initialize main class soot.jimple.infoflow.android.TestApps.Test Caused by: java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserException

### ISSUE THREAD

**Issue by OsamaDroidEgypt** [secure-software-engineering/soot-infoflow-android#177]
**when i run from CMD on Win**
`java -Xmx4g -cp soot-bundle-1.0.jar;soot-infoflow.jar;soot-infoflow-android.jar;slf4j-api-1.7.5.jar;slf4j-simple-1.7.5.jar;axml-2.0.jar soot.jimple.infoflow.android.TestApps.Test "C:\Users\OsMat\Downloads\release2.5.5" C:\Users\OsMat\AppData\Local\Android\Sdk\platforms`
**I got an error :**
`Error: Unable to initialize main class soot.jimple.infoflow.android.TestApps.Test Caused by: java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserException`

**Comment by Osama-Mattar** [comment]
😁😊😋😎😎

**Comment by StevenArzt** [comment]
There seems to be a JAR file missing on your JVM classpath: AXMLPrinter2.jar. It is located in the "lib" folder of the project. We will switch to Maven in the next version of FlowDroid to resolve such problems.
