### ISSUE TITLE
[Question] How to get callers of a method

### ISSUE THREAD

**Issue by sasidv** [secure-software-engineering/soot-infoflow-android#184]
I know this is basic question but I am impressed that I couldn't find a solid answer for this.

I need a way to obtain callers of a method. What is the most effective way of doing this. I know, I can  do this by iterating the call graph, But I am sure there should be more effective way other than that. 

for an exampel
```
foo
{
 method_a()
}

doo
{
mehod_a()
}
```

I need to get the callers (foo & doo) by giving the method_a as an argument. Could somebody help me on this ?

**Comment by sasidv** [comment]
@mbenz89  probably you may have a quick answer for this.

**Comment by StevenArzt** [comment]
There is a class called InfoflowCFG, which contains a method getCallersOf().
