### ISSUE TITLE
call graph of an android apk without mentioning sources and sinks

### ISSUE THREAD

**Issue by aatiranum** [secure-software-engineering/soot-infoflow-android#187]
I want to generate call graph of an android apk without mentioning source and sink in dot format. I have seen the links 
https://stackoverflow.com/questions/31456061/android-apk-control-flow-graph-with-soot
https://github.com/secure-software-engineering/soot-infoflow-android/issues/76

I have downloaded soot.infoflow.android but the setUpApplication.java does not contain the function getCallGraph(). 

How to construct  Interprocedural CFG in dot format in the new version of FlowDroid on GitHub?

**Comment by maldil** [comment]
You can use `Scene.v().getCallGraph()`

**Comment by StevenArzt** [comment]
You can use SetupApplication.constructCallgraph() first to create the callgraph and then use Scene.v().getCallGraph() to obtain a reference to it.
