### ISSUE TITLE
Import project into eclipse （mac os）has Errors

### ISSUE THREAD

**Issue by YYXWJ** [secure-software-engineering/soot-infoflow-android#197]
![image](https://user-images.githubusercontent.com/19309378/41038318-58c7f5f0-69c8-11e8-9612-939ee141d46e.png)

I can run this project on windows 7 eclipse .but I try lots of ways to solve this problems on mac os,but no used . Could you please tell me how to run this project on mac os?

**Comment by StevenArzt** [comment]
This is an old repository. Please use this repository instead: https://github.com/secure-software-engineering/FlowDroid
