### ISSUE TITLE
A question about how to install Flowdroid, 

### ISSUE THREAD

**Issue by RandoChoi** [secure-software-engineering/soot-infoflow-android#201]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/.m2/repository/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/sootclasses-trunk-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[main] INFO soot.jimple.infoflow.taintWrappers.EasyTaintWrapper - Loaded wrapper entries for 89 classes and 12 exclusions.

I run the test case, but it go wrong.

**Comment by StevenArzt** [comment]
This is an outdated version of FlowDroid. Please use https://github.com/secure-software-engineering/FlowDroid instead.
