### ISSUE TITLE
Generating DirectedGraph<Unit> from iCFG

### ISSUE THREAD

**Issue by AbdulAli** [secure-software-engineering/soot-infoflow-android#205]
There has been a lot of help about generating control-flow graph from .APK #129 #155 
But, according to the current implementation `analyzer.calculateSourcesSinksEntrypoints` is removed.

@StevenArzt further mention in [question](https://github.com/secure-software-engineering/FlowDroid/issues/56#event-1756008155)  that CFG creation process is made reliable and we can construct iCFG from SetupApplication instance directly. But for generating intra-procedural CFG (DirectedGraph<Unit>), we call `icfg.getOrCreateUnitGraph(targetMethod);`. My question is that what is the target method here.

**Comment by AbdulAli** [comment]
I found the answer to my question in mailing list by @StevenArzt 

> In Android, there is no such single entry point into the app that
> could serve as a natural start and end point of a path. That’s also why
> there is no easy access to “all paths” in FlowDroid: It’s totally unclear
> what such paths should look like. We do have a couple of path notations,
> though:
>
>
>
> 1.       Taint propagation paths. They start at a source and go wherever
> the respective taint goes.
>
> 2.       Source-to-sink paths: A subset of the taint propagation paths,
> namely those that end up in a sink.
>
>
>
> Unrelated to data flows, there are also other path notations one could
> think of:
>
>
>
> 1.       Control flow paths through a single method. That’s available in
> the iCfg.
>
> 2.       Control flow paths from the beginning of the dummy main method
> which emulates the Android lifecycle to the end of that dummy main method.
> You can build that from the iCfg. When using those, you however need to be
> really careful about the semantics of your results (i.e., what does such a
> path represent in the end?). This would essentially be a single trajectory
> through the app given a specific interaction of the Android OS and the user
> with the app. Usually, the set of those trajectories is of infinite size.
>

**Comment by wangchenguang123** [comment]
when i look your answer,i know what you speak,But when i code , i find i can not make it do,so may i please show the code what you write to me,then i can learn it.

**Comment by wangchenguang123** [comment]
@AbdulAli
