### ISSUE TITLE
Can't compile 'FlowDroid_1.0'

### ISSUE THREAD

**Issue by PeterParker369** [secure-software-engineering/soot-infoflow-android#208]
Can't compile FlowDroid_1.0. Please help. No main class.

**Comment by StevenArzt** [comment]
This is an outdated repository. FlowDroid has moved to https://github.com/secure-software-engineering/FlowDroid.

**Comment by PeterParker369** [comment]
Thank You for quick answer. I'm trying to compile https://github.com/dfbravo/KeyFinderDroid. So it looks like that 'soot-infoflow-android.jar' is changed a lot and doesn't contain some methods anymore. For example this lines:

> ...
SootMethod entryPoint = app.getEntryPointCreator().createDummyMain();
...
SetupApplication app = new SetupApplication(androidSdkPath,appPath);
app.calculateSourcesSinksEntrypoints(SourcesAndSinksFilePath);
...
