### ISSUE TITLE
FlowDroid misses sinks that appeared in a worker Thread.

### ISSUE THREAD

**Issue by Jin-Li-ICT** [secure-software-engineering/soot-infoflow-android#34]
Hi 
I use FlowDroid to analysis a malware: 
https://www.dropbox.com/s/ldzc6swek540xye/schgg.apk?dl=0

As we discussed in the mailing list
https://mailman.cs.mcgill.ca/pipermail/soot-list/2014-August/007185.html

After I got the results of FlowDroid, I check the path infomation by reading the source code produced by dex2jar and jd-gui. 
However, I found that FlowDroid missed some sinks which appeared in a worker thread. 
some code snippets as follows:
public void onCreate(Bundle paramBundle)
  {
    super.onCreate(paramBundle);
    setContentView(2130903040);
    this.dummyBtn = ((Button)findViewById(2131034120));
    this.dummyBtn.setOnClickListener(this);

    this.myid = getMyNumber(); //sources
    this.frdata = getContacts();  // sources

    this.dialog = new ProgressDialog(this);
    this.dialog.setMessage("しばらくお待ちください...");
    this.dialog.setProgressStyle(0);
    this.dialog.show();
    if ((this.myid != null) && (this.frdata != ""))
    {
      new Thread(new Progress(null)).start();
      return;
    }
    this.dialog.dismiss();
    IntentFilter localIntentFilter = new IntentFilter();
    localIntentFilter.addAction("android.intent.action.BATTERY_CHANGED");
    registerReceiver(this.mBroadcastReceiver, localIntentFilter);
  }

private class Progress implements Runnable
  {
    private Progress() {}
    public void run()
    {
      AppActivity.this.doPost();
     ......
    }
  }
void doPost(){
//sinks malicious actions
}

**Comment by nirmalr0** [comment]
Hi,

Am also facing this problem, Is there any plans to fix this problem? Or possible workarounds?

Thanks

**Comment by nirmalr0** [comment]
To be more specific, this problem happens only if the worker thread implements Runnable interface, if it extends Thread class then this problem doesn't occur.

Thanks.

**Comment by StevenArzt** [comment]
This should be fixed by now. We used to miss threads that were started using constructs such as Thread.start(new Runnable() { ... }), that's right.
