### ISSUE TITLE
Visualization for Flowdroid

### ISSUE THREAD

**Issue by sbachala2** [secure-software-engineering/soot-infoflow-android#39]
Hi,

I am looking into analyzing apps using Flowdroid. After anlazing some apps I thought having a visulizing tool for FlowDroid would be very useful for analysts instead of textual data, more like CallGraph from Source to Sink.

Is there any project in the pipeline for visualizing using graphviz or other visualizing methodologies.

Shakthi

**Comment by StevenArzt** [comment]
The flow visualizer will be available as a plugin to our CodeInspect tool: http://sseblog.ec-spride.de/2014/12/codeinspect/
