### ISSUE TITLE
Why using spark, not paddle to construct call graph ?

### ISSUE THREAD

**Issue by stream101** [secure-software-engineering/soot-infoflow-android#51]
paddle is object sensitive, and therefore more accurate than spark. I am curious why FlowDroid did not use paddle to construct call graph ?

**Comment by ericbodden** [comment]
Hi Xinjin.

FlowDroid uses a context-sensitive IFDS solver with an object-sensitive abstraction. This means that a context-sensitive call graph as such is not really required. Also there are some rather complex issues involved which make the "taint contexts" from FlowDroid somewhat incompatible with the calling contexts considered by Paddle.

Cheers,
Eric

> On 25.02.2015, at 07:38, Xinxin Jin <notifications@github.com> wrote:
> 
> paddle is object sensitive, and therefore more accurate than spark. I am curious why FlowDroid did not use paddle to construct call graph ?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Prof. Eric Bodden, Ph.D., http://sse.ec-spride.de/ http://bodden.de/
Head of Secure Software Engineering at Fraunhofer SIT, TU Darmstadt and EC SPRIDE
Tel: +49 6151 16-75422    Fax: +49 6151 869-127
Room B5.11, Fraunhofer SIT, Rheinstraße 75, 64295 Darmstadt
