### ISSUE TITLE
Not able to run flowdroid on Linux

### ISSUE THREAD

**Issue by krishnavaidy** [secure-software-engineering/soot-infoflow-android#53]
Following the wiki, I am able to run flowdroid with the nightly binaries on Windows, but I am not able to run it on my Ubuntu 12.04 machine.

Running this (replacing ; with : for Linux),
java -cp soot-trunk.jar: soot-infoflow.jar: soot-infoflow-android.jar: slf4j-api-1.7.5.jar: slf4j-simple 1.7.5.jar: axml-2.0.jar soot.jimple.infoflow.android.TestApps.Test xyz.apk /home/local/username/android-sdk-linux/platforms

gives me 

Error: Could not find or load main class soot-infoflow.jar:

I am running java-7-openjdk-amd64 as my java compiler. I tried running it on a Red Hat machine too, to no success. 

I'd be really grateful if you could point me to what I am missing.

Thanks!

**Comment by StevenArzt** [comment]
The blanks in your Java classpath are wrong. You must not separate the individual JAR files with blanks, only with colons:  -cp soot-trunk.jar:soot-infoflow.jar:soot-infoflow-android.jar etc.

**Comment by krishnavaidy** [comment]
Thanks for taking the time to reply!

I tried removing the blanks, but I am still not able to get it to work.

Command:
java -cp soot-trunk.jar:soot-infoflow.jar:soot-infoflow-android.jar:slf4j-api-1.7.5.jar:slf4j-simple 1.7.5.jar:axml-2.0.jar soot.jimple.infoflow.android.TestApps.Test Zocalo-debug.apk ~/android-sdk-linux/platforms

Now I get,
Error: Could not find or load main class 1.7.5.jar:axml-2.0.jar

I tried running on openjdk and oracle version of Java 7, but I still get the same error.

**Comment by MarcMil** [comment]
There is still a blank in "slf4j-simple 1.7.5.jar".
Try to rename that file to slf4j-simple1.7.5.jar and try the command
java -cp soot-trunk.jar:soot-infoflow.jar:soot-infoflow-android.jar:slf4j-api-1.7.5.jar:slf4j-simple1.7.5.jar:axml-2.0.jar soot.jimple.infoflow.android.TestApps.Test Zocalo-debug.apk ~/android-sdk-linux/platforms

**Comment by OxfordNJ** [comment]
I have a simple question:
My command is:
                java -cp soot-2.5.0.jar soot.Main
But i got an error:
               Could not find or load main class soot.Main
What happened with it? Can you give me  a help?
