### ISSUE TITLE
No Results Found (using test APKs)

### ISSUE THREAD

**Issue by TheBananaStand** [secure-software-engineering/soot-infoflow-android#54]
After downloading the nightly build JAR files and the sources/sinks, taint wrappers and callbacks text files, I've attempted to run FlowDroid against the test APKs found [here](https://github.com/secure-software-engineering/soot-infoflow-android/tree/develop/testAPKs). Issuing the following command:

`java -cp soot-trunk.jar:soot-infoflow.jar:soot-infoflow-android.jar:slf4j-api-1.7.5.jar:slf4j-simple-1.7.5.jar:axml-2.0.jar soot.jimple.infoflow.android.TestApps.Test ReturnParameterTest.apk /usr/share/android-sdk/sdk/platforms`

I receive the following results:

`[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
[Spark] Pointer Assignment Graph in 0.0 seconds.
[Spark] Type masks in 0.0 seconds.
[Spark] Pointer Graph simplified in 0.0 seconds.
[Spark] Propagation in 0.0 seconds.
[Spark] Solution found in 0.0 seconds.
[main] INFO soot.jimple.infoflow.Infoflow - Callgraph has 82 edges
[main] INFO soot.jimple.infoflow.Infoflow - Looking for sources and sinks...
[main] INFO soot.jimple.infoflow.Infoflow - Source lookup done, found 3 sources and 1 sinks.
[main] INFO soot.jimple.infoflow.Infoflow - Taint wrapper hits: 12
[main] INFO soot.jimple.infoflow.Infoflow - Taint wrapper misses: 10
[main] INFO soot.jimple.infoflow.Infoflow - IFDS problem with 86 forward and 6 backward edges solved, processing 0 results...
[main] INFO soot.jimple.infoflow.data.pathBuilders.ContextSensitivePathBuilder - Context-sensitive path reconstructor started
[main] WARN soot.jimple.infoflow.Infoflow - No results found.
Analysis has run for 10.099379135 seconds
`

**Comment by StevenArzt** [comment]
The output of FlowDroid is correct. This APK file does not contain any leaks. It was created to test a specific case and check whether FlowDroid is able to avoid a false positive. If you are looking for test cases that do contain leaks, you can have a look at DroidBench: https://github.com/secure-software-engineering/DroidBench
