### ISSUE TITLE
error in AbstractInfoflowProblem::protected boolean canCastType(Type destType, Type sourceType)

### ISSUE THREAD

**Issue by mikhail247** [secure-software-engineering/soot-infoflow-android#56]
At least, two common cases are missing

|| destType instanceof ByteType && sourceType instanceof CharType
|| destType instanceof CharType && sourceType instanceof ByteType)

The fixed method should look like this:

if (destType instanceof PrimType && sourceType instanceof PrimType)
			if (sourceType instanceof LongType && destType instanceof IntType
					|| destType instanceof LongType && sourceType instanceof IntType
					|| destType instanceof ByteType && sourceType instanceof CharType
					|| destType instanceof CharType && sourceType instanceof ByteType)
				return true;

**Comment by StevenArzt** [comment]
Fixed. There are actually many more cases as you can cast numeric types pretty much arbitrarily. I thus made the check more generic: You're free to cast primitives as long as you are not casting anything to Boolean that is not a Boolean on its own.
