### ISSUE TITLE
issues in taint propagation on exit

### ISSUE THREAD

**Issue by mikhail247** [secure-software-engineering/soot-infoflow-android#57]
ex. public void foo(String str) { //smth goes here }
When IFDSSolver processes "return" stmt, it treats String as a mutable object, thus it builds an edge from a register representing str in the context of foo() to the str in the context of its caller. 

probably, AccessPath.java::public static boolean canContainValue(Value val) is not complete (String cases should be handled separately)

**Comment by StevenArzt** [comment]
Should be fixed now, thanks for the hint
