### ISSUE TITLE
Did someone try to input a directory?

### ISSUE THREAD

**Issue by feng-zhe** [secure-software-engineering/soot-infoflow-android#61]
Hello everyone

I find there may be a bug in soot.jimple.infoflow.android.TestApps.Test, line 157.  It tries to extract the extension before determining whether it is a directory.  So is there a possibility that it will crash when I input a directory containing some apk files?  This causes the function "lastIndexOf" returns -1 and makes "subString" throw an exception.

**Comment by StevenArzt** [comment]
No, the idea is that we check for three possibilities: (1) You can directly specify an APK file to be analyzed (2) You can specify a directory. If so, all APK files within that directory will be analyzed. (3) You can specify a text file containing the full paths to some APK files that will then all be analyzed.
