### ISSUE TITLE
The sources and sinks in SourcesAndSinks.txt start with a "%".

### ISSUE THREAD

**Issue by jxnu707** [secure-software-engineering/soot-infoflow-android#66]
hi,
in the file "SourcesAndSinks.txt" of soot-infoflow-android-develop,i found many sources and sinks defined in it were started with a "%".What does it mean?
And,in soot.jimple.infoflow.android.data.parsers.PermissionMethodParser
private void parse() {
		sourceList = new HashSet<SourceSinkDefinition>(INITIAL_SET_SIZE);
		sinkList = new HashSet<SourceSinkDefinition>(INITIAL_SET_SIZE);
		neitherList = new HashSet<SourceSinkDefinition>(INITIAL_SET_SIZE);
		
		Pattern p = Pattern.compile(regex);
		Pattern pNoRet = Pattern.compile(regexNoRet);
		
		for(String line : this.data){	
			if (line.isEmpty() || line.startsWith("%"))
				continue;
			Matcher m = p.matcher(line);
			if(m.find()) {
				//....
			}
//other codes

why skip it when line.startsWith("%")?

**Comment by StevenArzt** [comment]
The % character at the beginning of a line comments out the complete line. Everything that follows the % character is ignored.
