### ISSUE TITLE
Config inner class in SourcesAndSinks.txt

### ISSUE THREAD

**Issue by flycode310** [secure-software-engineering/soot-infoflow-android#68]
sir, I want to config some functions in android,net.VpnService.Builder, but VpnService.Builder is a inner class, I don't know how to config it in SourcesAndSinks. 
Could you help please! Thank you very much !

**Comment by MarcMil** [comment]
Generally, inner classes have names like package name.OuterClass$InnerClass
So they are separated by Dollar symbols.

**Comment by flycode310** [comment]
Thanks, I get it.
