### ISSUE TITLE
Does FlowDroid have some interrupt mechanism？ 

### ISSUE THREAD

**Issue by jxnu707** [secure-software-engineering/soot-infoflow-android#72]
Hi,
   when I run soot-infoflow-android with all apks in a folder, the log like below.And since a  very long time(an hour?maybe more) it didn't keep going, i cancelled it manually.So,does it have some interrupt mechanism in soot-infoflow-android to fix problem like this?

.....
[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
[Spark] Pointer Assignment Graph in 0.0 seconds.
[Spark] Type masks in 0.0 seconds.
[Spark] Pointer Graph simplified in 0.0 seconds.
[Spark] Propagation in 2.1 seconds.
[Spark] Solution found in 2.1 seconds.
[pool-1-thread-1] INFO soot.jimple.infoflow.util.InterproceduralConstantValuePropagator - Removing side-effect free methods is enabled
Removed 545 call edges
[pool-1-thread-1] INFO soot.jimple.infoflow.Infoflow - Dead code elimination took 0.142989436 seconds
[pool-1-thread-1] INFO soot.jimple.infoflow.Infoflow - Callgraph has 5921 edges
[pool-1-thread-1] INFO soot.jimple.infoflow.Infoflow - Implicit flow tracking is NOT enabled
[pool-1-thread-1] INFO soot.jimple.infoflow.Infoflow - Running with a maximum access path length of 5
[pool-1-thread-1] INFO soot.jimple.infoflow.Infoflow - Using path-agnostic result collection
[pool-1-thread-1] INFO soot.jimple.infoflow.Infoflow - Recursive access path shortening is enabled
[pool-1-thread-1] INFO soot.jimple.infoflow.Infoflow - Looking for sources and sinks...
Layout control with ID 2131034325 not found
[pool-1-thread-1] INFO soot.jimple.infoflow.Infoflow - Source lookup done, found 220 sources and 163 sinks.

**Comment by ericbodden** [comment]
Hello.

It does not, and in fact in Java it is not easily possible to preempt threads.

In the past I have used the Unix “timeout” command in such situations. If you start your JVM with “timeout” then the OS will terminate the process after the given timeout.

Cheers,
Eric
