### ISSUE TITLE
Question about the file "SourcesAndSinks.txt" .

### ISSUE THREAD

**Issue by jxnu707** [secure-software-engineering/soot-infoflow-android#74]
hi,
   In flowdroid paper,it points out that this list inferred by Susi. And I checked the file  /SourceSinkFinder
/SourceSinkLists/Android 4.2/SourcesSinks/Ouput_CatSources_v0_9.txt, there are much more 
functions than it in SourcesAndSinks.txt of soot-infoflow-android.
   so the founctions in  "SourcesAndSinks.txt" is incomplete and just for a test or selected manually by some rules?

**Comment by StevenArzt** [comment]
The sources and sinks include in the SourcesAndSinks.txt file included with FlowDroid have been chosen to facilitate comparison with other data flow analysis tools. These are the most common sources and sinks. If you want a comprehensive list, use the one from SuSi.
