### ISSUE TITLE
Call Graph of an APK

### ISSUE THREAD

**Issue by chbruns** [secure-software-engineering/soot-infoflow-android#76]
I need the Call Graph of an Android App. Ist it possible to get a call graph as output from FlowDroid?

**Comment by StevenArzt** [comment]
Yes, FlowDroid can be used to construct the callgraph of an Android app:

```
             SetupApplication app = new SetupApplication
                           ("D:/Tools/adt-bundle-windows-x86_64-20140321/sdk/platforms",
                           "D:/Temp/com.tweakersoft.aroundme-1.apk");
             app.calculateSourcesSinksEntrypoints("D:/Arbeit/Android Analyse/soot-infoflow-android/SourcesAndSinks.txt");
             soot.G.reset();
             
             Options.v().set_src_prec(Options.src_prec_apk);
             Options.v().set_process_dir(Collections.singletonList("D:/Temp/com.tweakersoft.aroundme-1.apk"));
             Options.v().set_android_jars("D:/Tools/adt-bundle-windows-x86_64-20140321/sdk/platforms");
             Options.v().set_whole_program(true);
             Options.v().set_allow_phantom_refs(true);
             Options.v().set_output_format(Options.output_format_class);
             Options.v().setPhaseOption("cg.spark", "on");
             
             Scene.v().loadNecessaryClasses();
             
             SootMethod entryPoint = app.getEntryPointCreator().createDummyMain();
             Options.v().set_main_class(entryPoint.getSignature());
             Scene.v().setEntryPoints(Collections.singletonList(entryPoint));
             System.out.println(entryPoint.getActiveBody());
             
             PackManager.v().runPacks();
             System.out.println(Scene.v().getCallGraph().size()); 
```

**Comment by chbruns** [comment]
it worked, thanks!

**Comment by fenovsa** [comment]
@StevenArzt Hi,StevenArzt. I run the code, but the getEntryPointCreator is null ? I don't know about it. Can you help me?  Thank you!

**Comment by fenovsa** [comment]
@chbruns I run the above code but Scene.v().getCallGraph().size() is 0.

**Comment by StevenArzt** [comment]
@fenovsa If you have questions that are unrelated to the original thread (such as your current question), please open an own issue. Do not attach unrelated stuff to existing issues.

On topic: Are you sure you have called calculateSourcesSinksEntrypoints(), before trying to get the entry point creator?

**Comment by dhanyahari07** [comment]
i m getting the following error. plz help me
Exception in thread "main" java.lang.NoSuchMethodError: soot.util.HashMultiMap.putAll(Ljava/util/Map;)V

**Comment by aamirakbar** [comment]
Do anyone know how to resolve this issue (Also asked by dhanyahari07):

Exception in thread "main" java.lang.NoSuchMethodError: soot.util.HashMultiMap.putAll(Ljava/util/Map;)V

**Comment by StevenArzt** [comment]
@dhanyahari07, @aamirakbar Does this happen with the nightly build from our own build server or did you build Soot on your own? What did you do to create this error? What is the complete stack trace? Most likely, there's simply somethgin wrong with your Soot build - cleaning and re-building the project should solve it. In case it' our JAR that is broken, let me know.

**Comment by dhanyahari07** [comment]
@StevenArzt 
I did it from jar files

Is it the problem with jar???

From where I will get correct jars??

**Comment by StevenArzt** [comment]
@dhanyahari07 We had some issues with our pre-built JAR files. Can you please try again?

**Comment by dhanyahari07** [comment]
@StevenArzt sir where can i download the correct jar files?? any specific web site??

**Comment by dhanyahari07** [comment]
@StevenArzt itz working for me now. i downloaded the jars again and included, Thanks a lot

**Comment by dhanyahari07** [comment]
I did it from jar files

Is it the problem with jar???

From where I will get correct jars??

**Comment by MiniYellow** [comment]
Hi. I have used the lattest version of soot-infoflow-android. It seems that SetupApplication has been refactored. Method calculateSourcesSinksEntrypoints and createEntryPointCreator don't exist in SetupApplication. Could please provide an up-to-date way of constructing the callgraph ?

**Comment by mayank411** [comment]
Where do we have to write the above code??
