### ISSUE TITLE
Track specific string

### ISSUE THREAD

**Issue by ManSoSec** [secure-software-engineering/soot-infoflow-android#78]
Hi,

Is it possible to track a specific string ? I mean considering a flow from a string with a defined value like "way" to an API.

Thanks.

**Comment by StevenArzt** [comment]
It depends. In principle, you can write your own implementation of the ISourceSinkManager interface and mark all occurences of that string as tainted. This should work pretty well as long as your string is a constant value - otherwise, things get far more complicated.

**Comment by ManSoSec** [comment]
Thanks Steven! I understood it. Yes, it is a constant.

Thanks again.
