### ISSUE TITLE
Question about Slicing using Flowdroid

### ISSUE THREAD

**Issue by nuaa040840308** [secure-software-engineering/soot-infoflow-android#83]
Hi, I want to Whether I can make a program slicing using Flowdroid?
If yes, how to do this?
Thanks a lot

**Comment by StevenArzt** [comment]
FlowDroid is a data flow tracker, not a slicer. The goal of FlowDroid is to detect whether a sensitive value obtained from a source can influence a value passed to an untrusted sink, e.g., if your device id leaked to the internet. FlowDroid does not attempt to create executable slices or resolve any dependencies between source and sink that are not directly related to the data flow.
