### ISSUE TITLE
I run the project by tutorial, but I can't find result file in anywhere?

### ISSUE THREAD

**Issue by kai1** [secure-software-engineering/soot-infoflow-android#86]
I check the soot.jimple.infoflow.android.TestApps.Test, still can not found where result be saved.

**Comment by kai1** [comment]
And in the console end, it show this "
[main] INFO soot.jimple.infoflow.Infoflow - Looking for sources and sinks...
[main] ERROR soot.jimple.infoflow.Infoflow - No sinks found, aborting analysis
Analysis has run for 21.755557432 seconds"
I don't know does it correct OR failed?

**Comment by MarcMil** [comment]
The results get printed on the command line.
You message shows that FlowDroid did not find a potential data sink in your program such as sendTextMessage or similar. As such, there cannot be a flow according to FlowDroid.
You can convert your app via soot to Jimple (or use baksmali) to check whether there are method calls you would consider as data sinks but are not seen as data sinks by FlowDroid.
