### ISSUE TITLE
How to set “cmp” as taint operation?

### ISSUE THREAD

**Issue by majestyhao** [secure-software-engineering/soot-infoflow-android#90]
I notice b1 will not be treated as tainted in "$b1 = $l0 cmp 1L" statement when l0 is polluted. How to treat cmp as a taint operation?

Thanks.

**Comment by StevenArzt** [comment]
That should be the case by default. If you have a piece of code that afterwards passes $b1 into a sink method, it should be reported as a leak. If not, please provide a full code example.

**Comment by majestyhao** [comment]
Can I email you the code?

**Comment by majestyhao** [comment]
It works well after attempting the updated version.
