### ISSUE TITLE
Support regular expression in SourcesAndSinks.txt?

### ISSUE THREAD

**Issue by majestyhao** [secure-software-engineering/soot-infoflow-android#91]
Is it possible to support regular expression in SourcesAndSinks.txt ?
For example, let 
\<de.ecspride.Activity1: android.view.View findViewById(int)\> -> _SOURCE_
be 
<*: android.view.View findViewById(int)> -> _SOURCE_.

Thanks.

**Comment by StevenArzt** [comment]
Regular expressions are currently not supported in the source/sink defintion files. However, note that source and sink definitions also apply to child classes. If you mark a method A.foo() as a source, all calls to B.foo() for a child class B of A will also be considered as sources unless B explicitly overwrites method foo(). In your example, this means that it is sufficient to declare the method findViewById() in class android.view.View as a source. This will automatically apply to all calls to findViewById() in all activities in your app.

Additionally, there is already an option to make FlowDroid consider all UI elements as sources. Have a look at the --layoutmode option of our test application or the setLayoutMatchingMode() method in the InfoflowAndroidConfiguration class.
